name: News Tracker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch-news-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run News tracker
        env:
          GNEWS_TOPICS: ${{ secrets.GNEWS_TOPICS }}
          GNEWS_KEYWORDS: ${{ secrets.GNEWS_KEYWORDS }}
          GNEWS_SITES: ${{ secrets.GNEWS_SITES }}
          GNEWS_LOCATIONS: ${{ secrets.GNEWS_LOCATIONS }}
          GNEWS_LIMIT: ${{ secrets.GNEWS_LIMIT }}
          GNEWS_FROM_DATE: ${{ secrets.GNEWS_FROM_DATE }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_NEWS_DATABASE_ID: ${{ secrets.NOTION_NEWS_DATABASE_ID }}
        run: |
          cd src
          python main_news.py
