name: YouTube Tracker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch-youtube-videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run YouTube tracker
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_IDS: ${{ secrets.YOUTUBE_CHANNEL_IDS }}
          YOUTUBE_QUERIES: ${{ secrets.YOUTUBE_QUERIES }}
          YOUTUBE_VIDEO_IDS: ${{ secrets.YOUTUBE_VIDEO_IDS }}
          YOUTUBE_LIMIT: ${{ secrets.YOUTUBE_LIMIT }}
          YOUTUBE_FROM_DATE: ${{ secrets.YOUTUBE_FROM_DATE }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_YOUTUBE_DATABASE_ID: ${{ secrets.NOTION_YOUTUBE_DATABASE_ID }}
        run: |
          cd src
          python main_youtube.py
